version: '3'
services:
  db:
    image: postgres:16.2
    env_file:
      - .db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
